FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
COPY --from=build /src/out .

ENV ASPNETCORE_ENVIRONMENT=Development
CMD ASPNETCORE_URLS=http://*:$PORT dotnet xsolla-school-backend-2021.dll
