version: "3.9"

services:
    aspnet_webapi:
        build: ./
        restart: always
        ports: 
        - 5000:80
        environment:
        - ASPNETCORE_URLS=http://80+
        - ASPNETCORE_ENVIRONMENT=Development
        command: ["dotnet", "./xsolla-school-backend-2021.dll"]